fun main(){
    println("Enter the student details:")
    print("Enter Enrollment no.: ")
    val enroll = readln()
    print("Enter Name: ")
    val name = readln()
    print("Enter branch: ")
    val branch = readln()
    print("Enter class: ")
    val cls = readln()
    print("Enter Batch: ")
    val bat = readln()
    print("Student's college name: ")
    val colnam = readln()
    print("Student's uni name: ")
    val uniname = readln()
    print("Student's age: ")
    val age = readln()

    println("\nDetails of student are:")
    println("Enrollment number: $enroll")
    println("Name: $name")
    println("Branch: $branch")
    println("Class: $cls")
    println("Batch: $bat")
    println("College name: $colnam")
    println("University name: $uniname")
    println("Age: $age")
}